site_with_weather_info/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('weather/', include('weather.urls')),
    path('admin/', admin.site.urls),
]

weather/urls.py
from django.urls import path

from . import views

app_name = 'weather'
urlpatterns = [
    path('', views.index, name='index'),
    path('get-default/', views.get_info_about_default_location, name='get_default'),
    path('show-default/', views.show_info_about_default_location, name='show_default'),
    path('search-weather-results/', views.search_location_for_get_weather, name='search_results_for_get_weather'),
    path('search-results/', views.search_location_for_change_settings, name='search_results_for_change_settings'),
    path('get-another/', views.get_info_about_another_location, name='get_another'),
    path('show-all/', views.show_all_saved_info_about_locations, name='show_all'),
    path('show-favorite-locations/', views.show_info_about_favorite_locations, name='show_favorite'),
    path('settings/', views.go_to_settings, name='settings'),
    path('change-api-key/', views.change_api_key_in_settings, name='change_api_key'),
    path('change-default-location/', views.change_default_location_in_settings, name='change_default_location'),
    path('change-cron-settings/', views.change_cron_settings, name='change_cron_settings'),
    path('delete-from-cron/', views.delete_favorite_location_from_cron_settings, name='delete_from_cron'),
    path('search-favorite-location/', views.search_location_for_add_favorite_in_cron_settings, name='search_results_for_add_favorite'),
    path('add-favorite-location/', views.add_favorite_location_in_cron_settings, name='add_favorite_location'),
]

weather/models.py
from django.db import models


class Location(models.Model):
    location_key = models.CharField(max_length=8, primary_key=True)
    location_name = models.CharField(max_length=256)

    def __str__(self):
        return self.location_name


class Weather(models.Model):
    date_of = models.CharField(max_length=10)
    t_min = models.CharField(max_length=10)
    t_max = models.CharField(max_length=10)
    pressure = models.CharField(max_length=30)
    description = models.CharField(max_length=256)
    location_key = models.ForeignKey(Location, on_delete=models.CASCADE)

    def save_info_in_database(self):
        self.save()


class Settings(models.Model):
    API_key = models.CharField(max_length=32)
    default_location_key = models.ForeignKey(Location, on_delete=models.CASCADE, null=True)


class FavoriteLocation(models.Model):
    favorite_location_key = models.CharField(max_length=8)

weather/views.py
import datetime

from django.utils.datastructures import MultiValueDictKeyError
from django.shortcuts import render

from weather.check_new_api_key import check_new_api_key_on_errors
from weather.models import Location, Settings, Weather, FavoriteLocation
from weather.search_location import search_location_by_name
from weather.send_request_for_weather import send_request_about_weather_in_location


def index(request):
    try:
        setting = Settings.objects.get()  # получение настроек приложения из БД
        if setting:
            default_location_key = setting.default_location_key_id
            location = Location.objects.filter(
                location_key__exact=default_location_key)  # получение данных из БД о названии локации по умолчанию
            default_location_name = str(location[0])
            return render(request, 'weather/index.html', {'default_location_name': default_location_name})
    except:
        return render(request, 'weather/index.html', {'default_location_name': 'не определена'})


def get_info_about_default_location(request):
    setting = Settings.objects.get()  # получение настроек приложения из БД
    default_location_key = setting.default_location_key_id
    location = Location.objects.filter(
        location_key__exact=default_location_key)  # получение данных из БД о названии локации по умолчанию
    default_location_name = str(location[0])
    # запрос информации о погоде с сайта accuweather.com
    url_forecast = 'http://dataservice.accuweather.com/forecasts/v1/daily/1day/'
    url_current_conditions = 'http://dataservice.accuweather.com/currentconditions/v1/'
    answer_for = send_request_about_weather_in_location(url_forecast, default_location_key)
    answer_cc = send_request_about_weather_in_location(url_current_conditions, default_location_key)
    d1 = datetime.datetime.strptime(answer_for['DailyForecasts'][0]['Date'],
                                    "%Y-%m-%dT%H:%M:%S%z")  # переводим дату в удобный формат
    date_of = d1.strftime('%d.%m.%Y')
    t_min = str(answer_for['DailyForecasts'][0]['Temperature']['Minimum']['Value']) + ' °' + \
            answer_for['DailyForecasts'][0]['Temperature']['Minimum']['Unit']
    t_max = str(answer_for['DailyForecasts'][0]['Temperature']['Maximum']['Value']) + ' °' + \
            answer_for['DailyForecasts'][0]['Temperature']['Maximum']['Unit']
    pressure = str(round(answer_cc[0]['Pressure']['Metric']['Value'] * 0.75006375541921)) + ' мм рт.ст. ' + \
               answer_cc[0]['PressureTendency']['LocalizedText']
    description = 'Днём: ' + answer_for['DailyForecasts'][0]['Day']['LongPhrase'] + '. Ночью: ' + \
                  answer_for['DailyForecasts'][0]['Night']['LongPhrase'] + '.'
    Weather.objects.create(date_of=date_of, t_min=t_min, t_max=t_max, pressure=pressure,
                           description=description,
                           location_key_id=default_location_key)  # сохраняем информацию о погоде в БД
    return render(request, 'weather/get_info_about_location.html',
                  {'location_name': default_location_name,
                   'date_of': date_of,
                   't_min': t_min,
                   't_max': t_max,
                   'pressure': pressure,
                   'description': description})


def show_info_about_default_location(request):
    setting = Settings.objects.get()  # получение настроек приложения из БД
    default_location_key = setting.default_location_key_id
    location = Location.objects.filter(
        location_key__exact=default_location_key)  # получение данных из БД о названии локации по умолчанию
    default_location_name = str(location[0])
    all_info_about_default = Weather.objects.filter(
        location_key__exact=default_location_key)  # получение данных из БД о погоде в локации по умолчанию
    return render(request, 'weather/show_info_about_default_location.html',
                  {'default_location_name': default_location_name,
                   'all_info_about_default': all_info_about_default})


def search_location_for_get_weather(request):
    search_this = request.POST['location']  # получаем данные из формы на странице index.html
    search_this = search_this.strip()  # удаляем пробелы в начале и конце строки
    search_res = search_location_by_name(search_this)  # поиск локации
    # обработка, если локация не найдена
    if search_res == '':
        return render(request, 'weather/index.html', {
            'error_message': "Такая локация не найдена"})
    # проверяем, чтобы строка не содержала латиницы
    elif search_res == 'not a cyrillic':
        return render(request, 'weather/index.html', {
            'error_message': "Значение может содержать только кириллические буквы"})
    else:
        return render(request, 'weather/search_location_for_get_weather.html',
                      {'search_result': search_res})


def get_info_about_another_location(request):
    try:
        found_location_data = request.POST[
            'location']  # получаем данные из формы на странице search_location_for_get_weather.html
        list_of_fl_data = found_location_data.split(':')  # разделяем строку на ключ локации и ее название
        found_location_key = list_of_fl_data[0]
        found_location_name = list_of_fl_data[1]
        # проверяем, сохранена ли такая локация в БД, если нет - сохраняем
        saved_location = Location.objects.filter(location_key__exact=found_location_key)
        if not saved_location:
            Location.objects.create(location_key=found_location_key, location_name=found_location_name)
        # запрос информации о погоде с сайта accuweather.com
        url_forecast = 'http://dataservice.accuweather.com/forecasts/v1/daily/1day/'
        url_current_conditions = 'http://dataservice.accuweather.com/currentconditions/v1/'
        answer_for = send_request_about_weather_in_location(url_forecast, found_location_key)
        answer_cc = send_request_about_weather_in_location(url_current_conditions, found_location_key)
        d1 = datetime.datetime.strptime(answer_for['DailyForecasts'][0]['Date'],
                                        "%Y-%m-%dT%H:%M:%S%z")  # переводим дату в удобный формат
        date_of = d1.strftime('%d.%m.%Y')
        t_min = str(answer_for['DailyForecasts'][0]['Temperature']['Minimum']['Value']) + ' °' + \
                answer_for['DailyForecasts'][0]['Temperature']['Minimum']['Unit']
        t_max = str(answer_for['DailyForecasts'][0]['Temperature']['Maximum']['Value']) + ' °' + \
                answer_for['DailyForecasts'][0]['Temperature']['Maximum']['Unit']
        pressure = str(round(answer_cc[0]['Pressure']['Metric']['Value'] * 0.75006375541921)) + ' мм рт.ст. ' + \
                   answer_cc[0]['PressureTendency']['LocalizedText']
        description = 'Днём: ' + answer_for['DailyForecasts'][0]['Day']['LongPhrase'] + '. Ночью: ' + \
                      answer_for['DailyForecasts'][0]['Night']['LongPhrase'] + '.'
        Weather.objects.create(date_of=date_of, t_min=t_min, t_max=t_max, pressure=pressure,
                               description=description,
                               location_key_id=found_location_key)  # сохраняем информацию о погоде в БД
        return render(request, 'weather/get_info_about_location.html',
                      {'location_name': found_location_name,
                       'date_of': date_of,
                       't_min': t_min,
                       't_max': t_max,
                       'pressure': pressure,
                       'description': description})
    except (KeyError, MultiValueDictKeyError):
        return render(request, 'weather/search_location_for_get_weather.html',
                      {'error_message': 'Ошибка: значение не было выбрано'})


def show_all_saved_info_about_locations(request):
    all_saved_info = Weather.objects.all().order_by(
        'date_of')  # получаем информацию о погоде из БД с сортировкой по дате
    all_locations_names = Location.objects.all()  # получаем названия всех локаций, сохраненных в БД
    return render(request, 'weather/show_all_saved_info.html',
                  {'all_saved_info': all_saved_info,
                   'all_locations_names': all_locations_names})


def go_to_settings(request):
    return render(request, 'weather/go_to_settings.html')  # переходим к странице настроек


def search_location_for_change_settings(request):
    search_this = request.POST['location']  # получаем данные из формы на странице go_to_settings.html
    search_this = search_this.strip()  # удаляем пробелы в начале и конце строки
    search_res = search_location_by_name(search_this)  # поиск локации
    # обработка, если локация не найдена
    if search_res == '':
        return render(request, 'weather/go_to_settings.html', {
            'error_message_location': "Такая локация не найдена"})
    # проверяем, чтобы строка не содержала латиницы
    elif search_res == 'not a cyrillic':
        return render(request, 'weather/go_to_settings.html', {
            'error_message_location': "Значение может содержать только кириллические буквы"})
    else:
        return render(request, 'weather/search_location_for_change_settings.html',
                      {'search_result': search_res})


def change_api_key_in_settings(request):
    setting = Settings.objects.get()  # получение настроек приложения из БД
    current_default_location_key = setting.default_location_key_id
    new_api_key = request.POST['api_key']  # получаем данные из формы на странице go_to_settings.html
    new_api_key = new_api_key.strip()
    error_message_api = check_new_api_key_on_errors(new_api_key)  # проверяем введенное значение
    if error_message_api != '':
        return render(request, 'weather/go_to_settings.html', {
            'error_message_api': error_message_api})
    else:
        Settings.objects.all().delete()  # удаляем предыдущие значения настроек из БД

weather/templates/weather/change_settings_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'weather/common.css' %}">
    <meta charset="UTF-8">
    <title>Настройки сохранены</title>
</head>
<body>
    <div class="container">
    Настройки сохранены. <br><br><br>
    <a href="{% url 'weather:settings' %}">Назад</a><br><br>
    <a href="{% url 'weather:index' %}">На главную</a>
    </div>
</body>
</html>

weather/templates/weather/get_info_about_location.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'weather/common.css' %}">
    <meta charset="UTF-8">
    <title>Погода в "{{ location_name }}" сейчас</title>
</head>
<body>
<div class="container">
    <ul>
        <li>Локация: {{ location_name }}</li><br>
        <li>Дата: {{ date_of }} </li>
        <li>Минимальная температура: {{ t_min }} </li>
        <li>Максимальная температура: {{ t_max }} </li>
        <li>Атмосферное давление: {{ pressure }} </li>
        <li>{{ description }} </li>
    </ul>
    <br><br>
    <a href="{% url 'weather:index' %}">Назад</a>
</div>
</body>
</html>

weather/templates/weather/go_to_settings.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'weather/common.css' %}">
    <meta charset="UTF-8">
    <title>Настройки</title>
</head>
<body>
<div class="container">
    <form action="{% url 'weather:change_api_key'  %}" method="post">
    {% csrf_token %}
        Изменить API key:<br>
        <input type="text" name="api_key">
        <button type="submit">Сохранить</button><br>
        <label>{{ error_message_api }}</label>
    </form>
    <br><br>
    <form action="{% url 'weather:search_results_for_change_settings' %}" method="post">
    {% csrf_token %}
        Изменить локацию по умолчанию:<br>
        <input type="text" name="location">
        <button type="submit">Найти</button>
    </form>
     <label>{{ error_message_location }}</label><br>
    <br>
    <a href="{% url 'weather:change_cron_settings' %}">Настройки планировщика</a>
    <br><br>
    <a href="{% url 'weather:index' %}">Назад</a>
</div>
</body>
</html>

weather/templates/weather/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'weather/common.css' %}">
    <title>Главная</title>
</head>
<body>
<div class="container">
        <h2>Локация по умолчанию: {{ default_location_name }}</h2>
    <ul>
        <li><a href="{% url 'weather:get_default' %}">Получить последние данные о погоде в локации по умолчанию</a></li>
        <li><a href="{% url 'weather:show_default' %}">Просмотреть сохранённые данные о погоде в локации по умолчанию</a></li><br>
        <li>Получить последние данные о погоде в другой локации:</li>
        <form action="{% url 'weather:search_results_for_get_weather' %}" method="post">
            {% csrf_token %}
            <input type="text" name="location"><br>
            <button type="submit">Найти</button>
        </form>
        <label>{{ error_message }}</label><br>
        <li><a href="{% url 'weather:show_all' %}">Просмотреть все сохранённые данные о погоде</a></li>
        <li><a href="{% url 'weather:settings'%}">Изменить настройки</a></li>
    </ul>
</div>
</body>
</html>

weather/templates/weather/search_location_for_add_in_cron_settings.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'weather/common.css' %}">
    <meta charset="UTF-8">
    <title>Поиск локации:</title>
</head>
<body>
<div class="container">
    <h3>Результаты поиска:</h3>
    <label>{{ error_message }}</label>
    <div class="search">
    <form id="search" action="{% url 'weather:add_favorite_location'  %}" method="post">
        {% csrf_token %}
        {% for key, value in search_result.items %}
            <input type="radio" name="add_location" id="{{ key }}" value="{{ key }}:{{ value }}">
            <label class="search" for="{{ key }}">{{ value }}</label><br><br>
        {% endfor %}
        <br>
    </form>
    </div>
    <button form="search" type="submit">Выбрать</button><br><br>
    <a href="{% url 'weather:index' %}">Назад</a>
</div>
</body>
</html>

weather/templates/weather/search_location_for_change_settings.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'weather/common.css' %}">
    <meta charset="UTF-8">
    <title>Поиск локации:</title>
</head>
<body>
<div class="container">
    <h3>Результаты поиска:</h3>
    <label>{{ error_message }}</label>
    <div class="search">
    <form id="search" action="{% url 'weather:change_default_location'  %}" method="post">
        {% csrf_token %}
        {% for key, value in search_result.items %}
            <input type="radio" name="change_location" id="{{ key }}" value="{{ key }}:{{ value }}">
            <label class="search" for="{{ key }}">{{ value }}</label><br><br>
        {% endfor %}
        <br>
    </form>
    </div>
    <button form="search" type="submit">Выбрать</button><br><br>
    <a href="{% url 'weather:index' %}">Назад</a>
</div>
</body>
</html>

weather/templates/weather/search_location_for_get_weather.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'weather/common.css' %}">
    <meta charset="UTF-8">
    <title>Поиск локации:</title>
</head>
<body>
<div class="container">
    <h3>Результаты поиска:</h3>
    <label>{{ error_message }}</label>
    <div class="search">
    <form id="search" action="{% url 'weather:get_another'  %}" method="post">
        {% csrf_token %}
        {% for key, value in search_result.items %}
            <input type="radio" name="location" id="{{ key }}" value="{{ key }}:{{ value }}">
            <label for="{{ key }}">{{ value }}</label><br><br>
        {% endfor %}
        <br>
    </form>
    </div>
    <button form="search" type="submit">Выбрать</button><br><br>
    <a href="{% url 'weather:index' %}">Назад</a>
</div>
</body>
</html>

weather/templates/weather/settings_for_cron.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'weather/common.css' %}">
    <meta charset="UTF-8">
    <title>Настройки планировщика</title>
</head>
<body>
<div class="container">
    <h3>Локации, сохраненные для планировщика задач:</h3><br>
    <label>{{ error_message }}</label>
    <div class="search">
    <form id="delete" action="{% url 'weather:delete_from_cron'  %}" method="post">
        {% csrf_token %}
        {% for key, value in favorite_locations.items %}
            <input type="radio" name="favlocation" id="{{ key }}" value="{{ key }}">
            <label class="search" for="{{ key }}">{{ value }}</label><br><br>
        {% endfor %}
        <br>
    </form>
    </div>
    <button form="delete" type="submit">Удалить</button><br><br><br><br>
    <form action="{% url 'weather:search_results_for_add_favorite' %}" method="post">
    {% csrf_token %}
        Добавить новую локацию в планировщик:<br>
        <input type="text" name="location">
        <button type="submit">Найти</button>
    </form>
     <label>{{ error_message_location }}</label><br>
    <br>
    <a href="{% url 'weather:index' %}">Назад</a>
</div>
</body>
</html>

weather/templates/weather/show_all_saved_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'weather/common.css' %}">
    <meta charset="UTF-8">
    <title>Сохраненные данные о погоде</title>
</head>
<body>
<div class="table">
    <h3>Все сохраненные данные о погоде:</h3>
    <table border="1" aria-colspan="10">
        <tr>
            <th>Дата</th>
            <th>Локация</th>
            <th>Температура min</th>
            <th>Температура max</th>
            <th>Атмосферное давление</th>
            <th>Описание</th>
        </tr>
        {% for row in all_saved_info %}
            <tr>
                <td>{{ row.date_of }}</td>
                <td>
                    {% for r in all_locations_names %}
                        {% if row.location_key_id == r.location_key %}
                            {{ r.location_name }}
                        {% endif %}
                    {% endfor %}
                    </td>
                <td>{{ row.t_min }}</td>
                <td>{{ row.t_max }}</td>
                <td>{{ row.pressure }}</td>
                <td>{{ row.description }}</td>
            </tr>
        {% endfor %}
    </table>
    <br>
    <a href="{% url 'weather:index' %}">Назад</a>
</div>
</body>
</html>

weather/templates/weather/show_info_about_default_location.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'weather/common.css' %}">
    <meta charset="UTF-8">
    <title>Сохраненные данные о погоде в "{{ default_location_name }}"</title>
</head>
<body>
<div class="table">
    <h3>Локация по умолчанию: {{ default_location_name }}</h3><br>
    <table border="1" aria-colspan="10">
        <tr>
            <th>Дата</th>
            <th>Минимальная температура</th>
            <th>Максимальная температура</th>
            <th>Атмосферное давление</th>
            <th>Описание</th>
        </tr>
        {% for row in all_info_about_default %}
            <tr>
                <td>{{ row.date_of }}</td>
                <td>{{ row.t_min }}</td>
                <td>{{ row.t_max }}</td>
                <td>{{ row.pressure }}</td>
                <td>{{ row.description }}</td>
            </tr>
        {% endfor %}
    </table>
    <br>
    <a href="{% url 'weather:index' %}">Назад</a>
</div>
</body>
</html>

weather/templates/weather/show_info_about_favorite_locations.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'weather/common.css' %}">
    <meta charset="UTF-8">
    <title>Погода в выбранных локациях</title>
</head>
<body>
<div class="table">
    <h3>Погода в выбранных локациях:</h3>
    <table border="1" aria-colspan="10">
        <tr>
            <th>Локация</th>
            <th>Температура min</th>
            <th>Температура max</th>
            <th>Атмосферное давление</th>
            <th>Описание</th>
        </tr>
        {% for row in info_about_favorite_locations %}
            <tr>
                <td>{{ row.location_name }}</td>
                <td>{{ row.t_min }}</td>
                <td>{{ row.t_max }}</td>
                <td>{{ row.pressure }}</td>
                <td>{{ row.description }}</td>
            </tr>
        {% endfor %}
    </table>
    <br>
    <a href="{% url 'weather:index' %}">Назад</a>
</div>
</body>
</html>